env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:tailwindcss/recommended
  - next/core-web-vitals
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
